function setup() {
    //write a Heading
    createP('Perlin Noise Flow Field').style('font-size', '32px');
    createDiv('Perlin Noise is a type of gradient noise developed by Ken Perlin in 1983 as a result of his frustration with the "machine-like" look of computer graphics at the time. He formally described his findings in a SIGGRAPH paper in 1985. Perlin noise is widely used in computer graphics for effects like fire, smoke, and clouds. It is also used in procedural texture generation, terrain generation, and more.').style('font-size', '16px');
    
    createDiv('Technical Description').style('font-size', '24px');
    createDiv('Perlin noise is a type of gradient noise, which is a type of noise with a gradient function. Gradient noise is the result of a function that maps a point in space to a gradient value. Perlin noise is generated by interpolating between these gradient values. The result is a smooth, continuous noise function that can be used to create natural-looking textures and patterns.').style('font-size', '16px');
    
    createDiv('How it works').style('font-size', '24px');
    createDiv('Perlin noise is generated by combining multiple octaves of noise. Each octave is a layer of noise with a different frequency and amplitude. The noise values from each octave are combined to create the final noise value. This process is repeated for multiple octaves to create a more complex noise pattern. The result is a smooth, continuous noise function that can be used to create natural-looking textures and patterns.').style('font-size', '16px');

}

function draw() {
    // background(220);

    if (keyIsPressed && key === '1') {
        window.location.href = "oneDNoise.html";
    }
    if (keyIsPressed && key === '2') {
        window.location.href = "twoDNoise.html";
    }
    if (keyIsPressed && key === '3') {
        window.location.href = "Noise1/perlineNoise.html";
    }
}